source "https://rubygems.org"

gem "pd"
gem "tagen", "~>2.0.2"
gem "optimism", "~>3.3.1"
gem "pa", "~>1.4.0"
gem "retort", "~>0.0.6"
gem "thor", "~>0.16.0"
gem "net-ssh", "~>2.5.2"
gem "blather", "~>0.8.0"
gem "mechanize", "~>2.5.1"
gem "highline", "~>1.6.14"
gem "reverse_markdown", "~>0.3.0"
gem "watir", "~>4.0.1"
gem "faraday", "~>0.8.4"
gem "faraday_middleware", "~>0.8.8"
gem "isbn", "~>2.0.7"
gem "sys-filesystem", "~>1.0.0"
gem "trakt"
gem "awesome_print" # hot fix for trakt

group :development do
	gem "rspec"
  gem "vcr"
  gem "webmock"
  gem "guard"
  gem "guard-rspec"
  gem "rb-inotify"
end

# gemspec
