source "https://rubygems.org"

gem "rails", "4.0.0"
gem "rails-api"
gem "sqlite3"
gem "active_model_serializers", :git => "git://github.com/rails-api/active_model_serializers.git"
gem "rack-cors", :require => "rack/cors"
gem "pd"
